### ISSUE TITLE
No response from clicking Green Sign in/Join button... 

### ISSUE THREAD

**Issue by daqattack** [worbli/portal-v2-uat#17]
Reproduce & Result: This happened a few times to me, I am not sure if I am the only one who encountered this... but when I tried to sign in again, or join using a different email address, as the pictures below show, after I clicked on the green Sign in/Join button, there was no response ... I used Google Chrome on my mac. Then I used Safari on a different mac it still had the same problem. 

Expected Result: I expect to click on both green buttons and get directed to where I want to be :) 

<img width="522" alt="屏幕快照 2019-04-23 上午10 15 34" src="https://user-images.githubusercontent.com/48925615/56602191-c594f080-65b1-11e9-8ed1-a3826b63cc19.png">
<img width="501" alt="屏幕快照 2019-04-23 上午10 16 11" src="https://user-images.githubusercontent.com/48925615/56602203-ca59a480-65b1-11e9-8d01-116c4a520fee.png">

**Comment by frictionle55** [comment]
Having the same issue here on a Desktop and cell phone. Tried on Chrome and on Firefox.

**Comment by tkaraivanov** [comment]
Should be ok now, it was a temporary issue
