### ISSUE TITLE
back-end user status changes not updated in the UI

### ISSUE THREAD

**Issue by rdewilder** [worbli/portal-v2-uat#2]
1. Create or identify a user that has failed KYC (onfido_status = rejected)
2. reset the onfido_status for the user so that they can redo KYC (onfido_status = rejected)
3. Make sure the user is looged out of the portal
4. Log user back into the portal and navigate to the identity tab.

**Results:** 
The user is presented with a failure message:  _"status: rejected"._
User is unable to redo KYC as the form is not rendered.

**Expected results**
The user should be presented with the KYC form.

**Comment by valworbli** [comment]
The new _onfido_status_ must be 'created'. The steps to reset a user's KYC status are in  https://github.com/worbli/adminBackEnd/issues/41
