### ISSUE TITLE
Join/Sign in button not enabled

### ISSUE THREAD

**Issue by daqattack** [worbli/portal-v2-uat#3]
1. Open up Google Chrome to enter email address and passwords to join in/sign in

Result: Neither button works when clicked. 

Expected Result: I should be able to click on both buttons, join in will give me an email notification, and sign in will give me an error saying that I don't have an account with Worbli, and must create one to join in first.

**Comment by daqattack** [comment]
So I found that the password must be at least 8 characters long with at least one uppercase and one number. Is this correct? Otherwise it doesn't work. It would be great if we have instructions on the UI.

**Comment by rdewilder** [comment]
We do need clear visible feedback whenever there are client-side validation requirements.

**Comment by tkaraivanov** [comment]
This is tracked in https://github.com/worbli/portalFrontEnd/issues/108
