### ISSUE TITLE
Cannot move forward after taking a selfie, the Submit button is not enabled. 

### ISSUE THREAD

**Issue by daqattack** [worbli/portal-v2-uat#4]
Reproduce: After using the webcam to take a picture of my ID, I took a selfie. 

Result: I cannot move forward. The image was left on screen. 

Observation: After I clicked randomly on the screen, I found my picture was successfully taken and I was ready to hit the submit button. However, the Submit button is not enabled. And I cannot move forward. 

Expected result: After taking the selfie, I expect the system to save the picture automatically, and I do not need to click anywhere to continue. And I need to be able to click through the Submit button in order to submit my application. 

<img width="705" alt="屏幕快照 2019-04-19 下午6 05 07" src="https://user-images.githubusercontent.com/48925615/56449429-b9691480-62cd-11e9-80fa-f826862f36e5.png">

**Comment by tkaraivanov** [comment]
This is tracked in https://github.com/worbli/portalFrontEnd/issues/120
